name: pi-doctor
base: core22
version: '1.0'
summary: A CLI tool for diagnosing Raspberry Pi system, camera, GPIO, thermal and Python environment issues
description: |
  Longer description of your app.

grade: stable
confinement: strict

apps:
  your-app:
    command: bin/your-executable

parts:
  your-app:
    plugin: dump
    source: .
