name: pi-doctor
base: core22
version: '1.0'
summary: Short description of your app
description: |
  Longer description of your app.

grade: stable
confinement: strict

apps:
  your-app:
    command: bin/your-executable

parts:
  your-app:
    plugin: dump
    source: .
